# Parameters
parameters:
  - name: Verbosity
    default: Minimal
    values:
      - Quiet
      - Minimal
      - Normal
      - Detailed
      - Diagnostic

# CI triggers
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - src/*
      - packages/*
      - targets/*
      - Directory.Build.props
      - Directory.Build.targets
      - dirs.proj
      - global.json

pool:
  vmImage: "windows-latest"

# Variables
variables:
  # Parameters
  Verbosity: ${{ parameters.Verbosity }}
  # Paths
  RootPath: $(System.DefaultWorkingDirectory)
  RootProject: $(RootPath)/dirs.proj
  OutputFolder: $(RootPath)/out
  PackagesOutputFolder: $(OutputFolder)/packages
  # MSBuild-related props
  BuildConfiguration: Release
  DotNetSdkVersion: 10.x
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Skip caching packages

steps:
  - task: UseDotNet@2
    displayName: "Install dotnet Sdk"
    enabled: false
    inputs:
      packageType: "sdk"
      version: $(DotNetSdkVersion)

  # Build
  - task: DotNetCoreCLI@2
    displayName: Build Packages
    inputs:
      command: build
      projects: $(RootProject)
      arguments: "--configuration $(BuildConfiguration) --verbosity $(Verbosity)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(PackagesOutputFolder)'
      ArtifactName: 'Packages'
      publishLocation: 'Container'
